### PR TITLE
Add earplugs support to back_to_game

### LINKED ISSUE #101: Back to game does not handle earplugs

### PR DESCRIPTION
**Pull request by veteran29**
Fixes #101

**When merged this pull request will:**
- title
- Does not handle edge case when player has no uniform, whatever.

### CODE REVIEW

**Comment by 3Mydlo3** [comment]
Is there any way we can plug them back so player doesn't have to? This would solve no uniform case.

**Comment by veteran29** [comment]
`_player setVariable ["ACE_hasEarPlugsIn", true, true];`
I could make it so back_to_game has a support for variables restoration. As separate PR.

**Comment by 3Mydlo3** [comment]
If so, then merging this PR would be pointless.

**Comment by veteran29** [comment]
Closing in favor of #108

**Pull request closed without merging**
